const axios = require('axios');
const FormData = require('form-data');
const sharp = require('sharp');
const fs = require('fs');

// Stability AI Stable Diffusion Provider
class StabilityAIProvider {
  constructor() {
    if (!process.env.STABILITY_API_KEY) {
      throw new Error('STABILITY_API_KEY is not set in environment variables');
    }
    this.apiKey = process.env.STABILITY_API_KEY;
    this.baseUrl = 'https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/image-to-image';
  }

  async editImage(imagePath, prompt, maskPath = null) {
    try {
      console.log('Stability AI: Processing image edit...');
      
      const formData = new FormData();
      
      // Read and prepare image
      const imageBuffer = await sharp(imagePath)
        .resize(1024, 1024, { fit: 'inside', withoutEnlargement: true })
        .png()
        .toBuffer();
      
      formData.append('init_image', imageBuffer, 'image.png');
      formData.append('text_prompts[0][text]', prompt);
      formData.append('text_prompts[0][weight]', '1');
      formData.append('cfg_scale', '7');
      formData.append('steps', '30');
      formData.append('samples', '1');

      // Add mask if provided
      if (maskPath) {
        console.log('Stability AI: Applying mask...');
        const maskBuffer = await sharp(maskPath)
          .resize(1024, 1024, { fit: 'inside', withoutEnlargement: true })
          .png()
          .toBuffer();
        
        formData.append('mask_image', maskBuffer, 'mask.png');
        formData.append('mask_source', 'MASK_IMAGE_BLACK');
      }

      // Call Stability AI API
      const response = await axios.post(this.baseUrl, formData, {
        headers: {
          ...formData.getHeaders(),
          'Authorization': `Bearer ${this.apiKey}`,
          'Accept': 'application/json'
        },
        maxContentLength: Infinity,
        maxBodyLength: Infinity
      });

      if (response.data.artifacts && response.data.artifacts.length > 0) {
        const imageBase64 = response.data.artifacts[0].base64;
        console.log('Stability AI: Edit successful');
        
        return {
          success: true,
          imageData: imageBase64,
          provider: 'stability'
        };
      } else {
        throw new Error('No image generated by Stability AI');
      }
    } catch (error) {
      console.error('Stability AI Error:', error.response?.data || error.message);
      throw new Error(`Stability AI editing failed: ${error.response?.data?.message || error.message}`);
    }
  }
}

module.exports = { StabilityAIProvider };
